#pragma once

#include <ZAudio/AutoWahEffect.h>
#include <ZAudio/BitCrusherEffect.h>
#include <ZAudio/BypassEffect.h>
#include <ZAudio/DelayEffect.h>
#include <ZAudio/DuckDelayEffect.h>
#include <ZAudio/DynamicsProcessorEffect.h>
#include <ZAudio/FilterEffect.h>
#include <ZAudio/FlangerEffect.h>
#include <ZAudio/LfoWahEffect.h>
#include <ZAudio/LooperEffect.h>
#include <ZAudio/PhaserEffect.h>
#include <ZAudio/PingPongDelayEffect.h>
#include <ZAudio/PitchShiftEffect.h>
#include <ZAudio/ReverseDelayEffect.h>
#include <ZAudio/RobotEffect.h>
#include <ZAudio/SequenceFilterEffect.h>
#include <ZAudio/StereoChorusEffect.h>
#include <ZAudio/StereoFlangerEffect.h>
#include <ZAudio/StereoPhaserEffect.h>
#include <ZAudio/TremoloEffect.h>
#include <ZAudio/TubePreampEffect.h>
#include <ZAudio/VibratoEffect.h>
#include <ZAudio/VolumeControlEffect.h>
#include <ZAudio/WhisperEffect.h>
#include <ZAudio/Spatial2dEffect.h>
#include <ZAudio/SerialEffect.h>
#include <ZAudio/ParallelEffect.h>
#include <ZAudio/MonoToStereoAdapter.h>